= Project Tremulator

== Description

The Tremulator is a digital Humanities tool developed by Ian D. Johnson and David F. Johnson
for collecting and visualizing irregular paleographical data on Medieval manuscripts.

== How to install with docker

=== Requirements

To be able to install the application on your server, you will need :

* docker & docker-compose
* git

On debian like system, you can install them with the following command :
`apt-get install git docker docker-compose`

You also need to create an openID OAuth application on Google.
You can follow this guide  https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid

In the application, you have to specify the Url of the server (ex: http://tremulator.english.fsu.edu & https://tremulator.english.fsu.edu),
but also the allowed calback url, like those one (ie. for the path `/authentication/callback` & `/authentication/silent_callback`)

 * http://tremulator.english.fsu.edu/authentication/callback
 * https://tremulator.english.fsu.edu/authentication/callback
 * http://tremulator.english.fsu.edu/authentication/silent_callback
 * https://tremulator.english.fsu.edu/authentication/silent_callback

=== Process

* Clone the repository in the folder `/opt`

`$>git clone https://github.com/Tenkhenk/Tremulator-2.0 /opt/tremulator`

* Create a linux user called `tremulator`

`$>useradd tremulator -d /opt/tremulator/ -M -r`

* Add the created user to the group `docker`

`$> usermod -aG docker tremulator`

* Change the owner of the folder `opt/tremulator`

`$>chown -R tremulator:tremulator tremulator/`

* Create the system script service :

[source,bash]
----
$> cd /etc/systemd/system/
$> vi tremulator.service
[Unit]
Description=tremulator
Requires=docker.service

After=docker.service
[Service]
Restart=always
User=tremulator
Group=tremulator
WorkingDirectory=/opt/tremulator/docker

# Shutdown container (if running) when unit is started
ExecStartPre=docker-compose -f docker-compose.yml down
# Start container when unit is started
ExecStart=docker-compose -f docker-compose.yml up
# Stop container when unit is stopped
ExecStop=docker-compose -f docker-compose.yml down

[Install]
WantedBy=multi-user.target
$> sudo systemctl enable tremulator.service
----

* Edit the configuration of the docker stack. You must change those values :

** `MODE=prod`
** `CLIENT_ID=@YOUR_OPEN_CLIENT_ID@`
** `CLIENT_SECRET=@YOUR_OPEN_CLIENT_SECRET@`

Where `@YOUR_OPEN_CLIENT_ID@` &  `@YOUR_OPEN_CLIENT_SECRET@` is the openID client id/secret generated by google.

You can also change the default passwords and also the heap size for the IIIF server.

* When it's done, you can start the stack by running this command : `systemctl start tremulator.service`

TIP: You can check the log of the process with the command `journalctl -u tremulator.service`

Wait some minutes (the build of the docker stack can takes ~10min), and open your favorite browser on http://localchost
(you can replace localhost by the name/ip of your server)

include::./docker/README.adoc[leveloffset=+1]

include::./frontend/README.adoc[leveloffset=+1]

include::./backend/README.adoc[leveloffset=+1]


`
