= Backend: API server

* API documentation is available at http://localhost:3000/api/docs
* OpenAPI API definition file is available at http://localhost:3000/api/swagger.json


== Framework

Backend uses the framework https://github.com/lukeautry/tsoa[TSOA] for the REST API.
It is based on :

* https://expressjs.com/[express.js] for the web server
* https://swagger.io/[Swagger] for the API live documentation
* https://www.typescriptlang.org/[Typescript]

To access the database, it uses https://typeorm.io/[TYPEORM] as active record.

== Code structure

Code is splitted in 3 main folders :

* *controllers* for the API endpoint
* *services* to manage interactions with others systems (like authentification of IIIF server)
* *entities* to define the database entities

There are also 3 important files

* *index.ts :* it's the starting point of the application
* *error-handler.ts :* Centralized all the error for the API
* *authenticiation.ts :* handle the authentication for each API request (if needed)

IMPORTANT: File `routes.ts` must not be edited, it is generated by the framework TSOA
