/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/validate_code": {
    post: operations["Validate_code"];
  };
  "/auth/whoami": {
    get: operations["Whoami"];
  };
  "/misc/ping": {
    get: operations["Ping"];
  };
  "/misc/echo": {
    post: operations["Echo"];
  };
}

export interface operations {
  Validate_code: {
    parameters: {};
    requestBody: {
      "application/json": components["schemas"]["ValidateCodeRequest"];
    };
    responses: {
      /**
       * Ok
       */
      "200": {
        "application/json": components["schemas"]["ValidateCodeResponse"];
      };
      /**
       * Internal Error
       */
      "500": unknown;
    };
  };
  Whoami: {
    parameters: {};
    responses: {
      /**
       * Ok
       */
      "200": {
        "application/json": components["schemas"]["User"];
      };
      /**
       * Unauthorized
       */
      "401": unknown;
      /**
       * Forbidden
       */
      "403": unknown;
      /**
       * Internal Error
       */
      "500": unknown;
    };
  };
  Ping: {
    parameters: {};
    responses: {
      /**
       * Ok
       */
      "200": {
        "application/json": string;
      };
    };
  };
  Echo: {
    parameters: {};
    requestBody: {
      "application/json": { [key: string]: any };
    };
    responses: {
      /**
       * Ok
       */
      "200": {
        "application/json": { [key: string]: any };
      };
    };
  };
}

export interface components {
  schemas: {
    ValidateCodeResponse: {
      access_token: string;
      expires_in: number;
      scope: string;
      token_type: string;
      id_token: string;
    };
    ValidateCodeRequest: {
      client_id: string;
      code: string;
      code_verifier: string;
      grant_type: string;
      redirect_uri?: string;
    };
    User: {
      email: string;
      firstname: string;
      lastname: string;
      avatar: string;
      access_token: string;
      expires_at: number;
    };
  };
}
