version: "2"
services:
  # IIIF Server
  iiif:
    build:
      context: ./iiif
      dockerfile: ./Dockerfile
      args:
        IIIF_CANTALOUPE_VERSION: ${IIIF_CANTALOUPE_VERSION}
    restart: ${RESTART_POLICY}
    volumes:
      - ${PROJECT_PATH}/docker/iiif/data:/opt/iiif/data
      - ${PROJECT_PATH}/docker/iiif/cantaloupe.properties:/opt/iiif/cantaloupe.properties
    env_file:
      - ${PROJECT_PATH}/docker/.env

  # Postgres server
  db:
    image: postgis/postgis:${POSTGRES_VERSION}
    restart: ${RESTART_POLICY}
    volumes:
      - ${PROJECT_PATH}/docker/db/data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: ${RESTART_POLICY}
    depends_on:
      - backend
    ports:
      - ${HOST_HTTP_PORT}:80
    volumes:
      - ${PROJECT_PATH}/docker/frontend/nginx.${MODE}.conf:/etc/nginx/nginx.conf
      - ${PROJECT_PATH}/frontend:/frontend
    env_file:
      - ${PROJECT_PATH}/docker/.env

  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: ${RESTART_POLICY}
    depends_on:
      - db
      - iiif
    volumes:
      - ${PROJECT_PATH}/backend:/backend
      - ${PROJECT_PATH}/docker/iiif/data:/data
    env_file:
      - ${PROJECT_PATH}/docker/.env
