version: "2"
services:
  # Frontend
  iiif:
    build:
      context: ./iiif
      dockerfile: ./Dockerfile
      args:
        IIIF_CANTALOUPE_VERSION: ${IIIF_CANTALOUPE_VERSION}
    restart: ${RESTART_POLICY}
    volumes:
      - ${PROJECT_PATH}/docker/iiif/data:/opt/iiif/data
      - ${PROJECT_PATH}/docker/iiif/cantaloupe.properties:/opt/iiif/cantaloupe.properties
    env_file:
      - ${PROJECT_PATH}/docker/.env

  # Frontend
  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    restart: ${RESTART_POLICY}
    ports:
      - ${HOST_HTTP_PORT}:80
    volumes:
      - ${PROJECT_PATH}/docker/front/nginx.${MODE}.conf:/etc/nginx/nginx.conf
      - ${PROJECT_PATH}/front:/front
    env_file:
      - ${PROJECT_PATH}/docker/.env
