version: "2"
services:
  iiif:
    ports:
      - ${IIIF_PORT}:${IIIF_PORT}
  frontend:
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
      - "${HOST_HTTP_PORT}:80"
  backend:
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
